# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaInicial.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(919, 588)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameVideo = QtWidgets.QFrame(self.groupBox_2)
        self.frameVideo.setMinimumSize(QtCore.QSize(301, 211))
        self.frameVideo.setFrameShape(QtWidgets.QFrame.Box)
        self.frameVideo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVideo.setObjectName("frameVideo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameVideo)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.imagemMidia = QtWidgets.QLabel(self.frameVideo)
        self.imagemMidia.setText("")
        self.imagemMidia.setPixmap(QtGui.QPixmap("icones/play.png"))
        self.imagemMidia.setScaledContents(False)
        self.imagemMidia.setAlignment(QtCore.Qt.AlignCenter)
        self.imagemMidia.setWordWrap(False)
        self.imagemMidia.setOpenExternalLinks(False)
        self.imagemMidia.setObjectName("imagemMidia")
        self.verticalLayout_3.addWidget(self.imagemMidia)
        self.verticalLayout_6.addWidget(self.frameVideo)
        self.texto = QtWidgets.QLabel(self.groupBox_2)
        self.texto.setObjectName("texto")
        self.verticalLayout_6.addWidget(self.texto, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.slideMusica = QtWidgets.QSlider(self.groupBox_2)
        self.slideMusica.setMinimumSize(QtCore.QSize(314, 22))
        self.slideMusica.setToolTip("")
        self.slideMusica.setPageStep(1)
        self.slideMusica.setOrientation(QtCore.Qt.Horizontal)
        self.slideMusica.setObjectName("slideMusica")
        self.verticalLayout_5.addWidget(self.slideMusica)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.botaoPlay = QtWidgets.QPushButton(self.groupBox_2)
        self.botaoPlay.setStyleSheet("")
        self.botaoPlay.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icones/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botaoPlay.setIcon(icon)
        self.botaoPlay.setIconSize(QtCore.QSize(18, 18))
        self.botaoPlay.setAutoRepeat(False)
        self.botaoPlay.setObjectName("botaoPlay")
        self.horizontalLayout.addWidget(self.botaoPlay)
        self.botaoStop = QtWidgets.QPushButton(self.groupBox_2)
        self.botaoStop.setStyleSheet("")
        self.botaoStop.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icones/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botaoStop.setIcon(icon1)
        self.botaoStop.setIconSize(QtCore.QSize(18, 18))
        self.botaoStop.setAutoRepeat(False)
        self.botaoStop.setObjectName("botaoStop")
        self.horizontalLayout.addWidget(self.botaoStop)
        self.botaoRedimencionar = QtWidgets.QPushButton(self.groupBox_2)
        self.botaoRedimencionar.setStyleSheet("")
        self.botaoRedimencionar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icones/94519.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botaoRedimencionar.setIcon(icon2)
        self.botaoRedimencionar.setIconSize(QtCore.QSize(18, 18))
        self.botaoRedimencionar.setCheckable(True)
        self.botaoRedimencionar.setChecked(False)
        self.botaoRedimencionar.setAutoRepeat(False)
        self.botaoRedimencionar.setObjectName("botaoRedimencionar")
        self.horizontalLayout.addWidget(self.botaoRedimencionar)
        self.botaoPlayList = QtWidgets.QPushButton(self.groupBox_2)
        self.botaoPlayList.setStyleSheet("")
        self.botaoPlayList.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icones/playlist-2223100-1861902.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botaoPlayList.setIcon(icon3)
        self.botaoPlayList.setIconSize(QtCore.QSize(18, 18))
        self.botaoPlayList.setCheckable(True)
        self.botaoPlayList.setChecked(False)
        self.botaoPlayList.setAutoRepeat(False)
        self.botaoPlayList.setObjectName("botaoPlayList")
        self.horizontalLayout.addWidget(self.botaoPlayList)
        self.botaoIniciarPlayback = QtWidgets.QPushButton(self.groupBox_2)
        self.botaoIniciarPlayback.setStyleSheet("")
        self.botaoIniciarPlayback.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icones/playback.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botaoIniciarPlayback.setIcon(icon4)
        self.botaoIniciarPlayback.setIconSize(QtCore.QSize(18, 18))
        self.botaoIniciarPlayback.setCheckable(True)
        self.botaoIniciarPlayback.setChecked(False)
        self.botaoIniciarPlayback.setAutoRepeat(False)
        self.botaoIniciarPlayback.setObjectName("botaoIniciarPlayback")
        self.horizontalLayout.addWidget(self.botaoIniciarPlayback)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMaximumSize(QtCore.QSize(21, 21))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icones/note-beam.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.comboMusica = QtWidgets.QComboBox(self.groupBox_2)
        self.comboMusica.setEditable(True)
        self.comboMusica.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboMusica.setFrame(True)
        self.comboMusica.setObjectName("comboMusica")
        self.horizontalLayout_3.addWidget(self.comboMusica)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMaximumSize(QtCore.QSize(21, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icones/legendas.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboLegenda = QtWidgets.QComboBox(self.groupBox_2)
        self.comboLegenda.setEditable(True)
        self.comboLegenda.setCurrentText("")
        self.comboLegenda.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboLegenda.setFrame(True)
        self.comboLegenda.setObjectName("comboLegenda")
        self.horizontalLayout_4.addWidget(self.comboLegenda)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.botaoVolume = QtWidgets.QPushButton(self.groupBox_2)
        self.botaoVolume.setStyleSheet("")
        self.botaoVolume.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icones/iconfinder-volume-max-sound-speaker-audio-4593170_122277.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botaoVolume.setIcon(icon5)
        self.botaoVolume.setIconSize(QtCore.QSize(18, 18))
        self.botaoVolume.setAutoRepeat(False)
        self.botaoVolume.setObjectName("botaoVolume")
        self.horizontalLayout_7.addWidget(self.botaoVolume)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.listaTrecho = QtWidgets.QListWidget(self.groupBox_2)
        self.listaTrecho.setMinimumSize(QtCore.QSize(251, 320))
        self.listaTrecho.setObjectName("listaTrecho")
        self.horizontalLayout_6.addWidget(self.listaTrecho)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.botaoAdicionar = QtWidgets.QToolButton(self.groupBox_3)
        self.botaoAdicionar.setStyleSheet("border-radius: 10px;")
        self.botaoAdicionar.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icones/add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botaoAdicionar.setIcon(icon6)
        self.botaoAdicionar.setObjectName("botaoAdicionar")
        self.horizontalLayout_8.addWidget(self.botaoAdicionar)
        self.botaoRemover = QtWidgets.QToolButton(self.groupBox_3)
        self.botaoRemover.setStyleSheet("border-radius: 10px;")
        self.botaoRemover.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icones/remove-symbol_icon-icons.com_73439.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botaoRemover.setIcon(icon7)
        self.botaoRemover.setObjectName("botaoRemover")
        self.horizontalLayout_8.addWidget(self.botaoRemover)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.listaPlaylist = QtWidgets.QListWidget(self.groupBox_3)
        self.listaPlaylist.setObjectName("listaPlaylist")
        self.verticalLayout_8.addWidget(self.listaPlaylist)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.lista_coletanea = QtWidgets.QListWidget(self.tab_2)
        self.lista_coletanea.setIconSize(QtCore.QSize(172, 250))
        self.lista_coletanea.setMovement(QtWidgets.QListView.Static)
        self.lista_coletanea.setResizeMode(QtWidgets.QListView.Adjust)
        self.lista_coletanea.setLayoutMode(QtWidgets.QListView.Batched)
        self.lista_coletanea.setViewMode(QtWidgets.QListView.IconMode)
        self.lista_coletanea.setModelColumn(0)
        self.lista_coletanea.setUniformItemSizes(True)
        self.lista_coletanea.setWordWrap(False)
        self.lista_coletanea.setObjectName("lista_coletanea")
        item = QtWidgets.QListWidgetItem()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("iconesColetanea/adoradores.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon8)
        self.lista_coletanea.addItem(item)
        self.verticalLayout_4.addWidget(self.lista_coletanea)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_12.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.areaBusca = QtWidgets.QLineEdit(self.groupBox)
        self.areaBusca.setObjectName("areaBusca")
        self.horizontalLayout_2.addWidget(self.areaBusca)
        self.comboBanco = QtWidgets.QComboBox(self.groupBox)
        self.comboBanco.setObjectName("comboBanco")
        self.comboBanco.addItem("")
        self.comboBanco.addItem("")
        self.comboBanco.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBanco)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.botaoAdicionar_2 = QtWidgets.QToolButton(self.groupBox)
        self.botaoAdicionar_2.setStyleSheet("border-radius: 10px;")
        self.botaoAdicionar_2.setText("")
        self.botaoAdicionar_2.setIcon(icon6)
        self.botaoAdicionar_2.setObjectName("botaoAdicionar_2")
        self.verticalLayout_2.addWidget(self.botaoAdicionar_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listaBanco = QtWidgets.QListWidget(self.groupBox)
        self.listaBanco.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.listaBanco.setAcceptDrops(True)
        self.listaBanco.setObjectName("listaBanco")
        self.verticalLayout.addWidget(self.listaBanco)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.comboMusica.setCurrentIndex(-1)
        self.comboLegenda.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sn7.0.1"))
        self.texto.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.texto.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">tt</p></body></html>"))
        self.texto.setText(_translate("MainWindow", "Parado"))
        self.botaoPlay.setToolTip(_translate("MainWindow", "<html><head/><body><p>play/pause</p></body></html>"))
        self.botaoStop.setToolTip(_translate("MainWindow", "<html><head/><body><p>stop</p></body></html>"))
        self.botaoRedimencionar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ocultar Tela secundária</p></body></html>"))
        self.botaoPlayList.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ativa a playlist</p></body></html>"))
        self.botaoIniciarPlayback.setToolTip(_translate("MainWindow", "<html><head/><body><p>Iniciar com playback caso possivel</p></body></html>"))
        self.comboMusica.setToolTip(_translate("MainWindow", "<html><head/><body><p>trilha de audio, normalmente exibe Normal/Playback</p></body></html>"))
        self.comboLegenda.setToolTip(_translate("MainWindow", "<html><head/><body><p>Legendas</p></body></html>"))
        self.botaoVolume.setToolTip(_translate("MainWindow", "<html><head/><body><p>Mute</p><p><br/></p></body></html>"))
        self.listaTrecho.setToolTip(_translate("MainWindow", "<html><head/><body><p>Exibe os trechos da midia caso exista.</p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Playlist"))
        self.botaoAdicionar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Adicionar midia externa</p></body></html>"))
        self.botaoRemover.setToolTip(_translate("MainWindow", "<html><head/><body><p>Remover item da lista</p></body></html>"))
        self.listaPlaylist.setToolTip(_translate("MainWindow", "<html><head/><body><p>lista de midia</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Player"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Pesquise:"))
        self.lista_coletanea.setSortingEnabled(False)
        __sortingEnabled = self.lista_coletanea.isSortingEnabled()
        self.lista_coletanea.setSortingEnabled(False)
        item = self.lista_coletanea.item(0)
        item.setText(_translate("MainWindow", "item Teste1"))
        self.lista_coletanea.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Coletânea"))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "Sonoplastia"))
        self.groupBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Banco de dados</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Banco:"))
        self.areaBusca.setToolTip(_translate("MainWindow", "<html><head/><body><p>Clique Enter para procurar</p></body></html>"))
        self.comboBanco.setItemText(0, _translate("MainWindow", "Musica"))
        self.comboBanco.setItemText(1, _translate("MainWindow", "Trecho"))
        self.comboBanco.setItemText(2, _translate("MainWindow", "Album"))
        self.botaoAdicionar_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Adicionar a playList</p></body></html>"))
        self.listaBanco.setToolTip(_translate("MainWindow", "<html><head/><body><p>intens procurados</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
